# Site
name: "Valters Blog"
title: "~/"
description: "I write?"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
include: ["_pages"]
permalink: /:title/
url: www.tomsons.me
baseurl: ''

# Authors
authors:
  valters:
    name: Valters
    display_name: Valters
    avatar: 'assets/images/valters-avatar.jpg'
    email: valters.tomsons@protonmail.com
    web: https://github.com/valters-tomsons

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: rouge
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
